version: "2.1"
services:
  openssh-server:
    build:
      context: .
    container_name: openssh-server
    environment:
      - PUID=1000
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PGID=1000
      - TZ=Europe/London
      - USER_NAME=phab
      - SUDO_ACCESS=true
    ports:
      - 127.0.0.1:2222:2222
    restart: unless-stopped
    volumes:
      - ../land_queue/:/config/land_queue
